sudo: required
services:
  - docker
branches:
  only:
    - dev
    - stage
    - prod
env:
  global:
    - BRANCH=$TRAVIS_BRANCH
    - PULL_REQUEST=$TRAVIS_PULL_REQUEST
    - SHA=$TRAVIS_PULL_REQUEST_SHA

before_install:
  - echo $TRAVIS_PULL_REQUEST_BRANCH
  - echo $TRAVIS_PULL_REQUEST_SLUG
