sudo: required
services:
  - docker
branches:
  only:
    - dev
    - stage
    - prod
before_install:
  - docker build -t portal/test-react -f ./react/Dockerfile.dev ./react

script:
  - docker run portal/test-react npm run test -- --coverage

after_success:
  - docker build -t portal/${TRAVIS_BRANCH}-nginx ./nginx
  - docker build -t portal/${TRAVIS_BRANCH}-express ./express
  - docker build -t portal/${TRAVIS_BRANCH}-react ./react
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push portal/${TRAVIS_BRANCH}-nginx
  - docker push portal/${TRAVIS_BRANCH}-express
  - docker push portal/${TRAVIS_BRANCH}-react
#deploy:
#provider: elasticbeantalk
