version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
    restart: always
  express:
    build:
      dockerfile: Dockerfile.dev
      context: ./express
    ports:
      - '5000:5000'
    volumes:
      - ./express/src:/app/src
    environment:
      - PG_TYPE=postgres
      - PG_HOST=postges
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=portal
      - PG_PORT=5432
  react:
    build:
      dockerfile: Dockerfile.dev
      context: ./react
    ports:
      - '9000:9000'
    volumes:
      - ./react/src:/app/src
