version: '3.8'
services:
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
    restart: always
  express:
    build:
      dockerfile: Dockerfile.dev
      context: ./express
    ports:
      - '5000:5000'
    volumes:
      - ./express/src:/app/src
    env_file:
      - ./express/.env
  react:
    build:
      dockerfile: Dockerfile.dev
      context: ./react
    ports:
      - '3000:3000'
    volumes:
      - ./react/src:/app/src
