version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
  nginx:
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '8080:80'
    restart: always
  express:
    build:
      dockerfile: Dockerfile
      context: ./express
    ports:
      - '5000:5000'
    restart: always
  react:
    build:
      dockerfile: Dockerfile
      context: ./react
    ports:
      - '9000:9000'
    restart: always
