version: '3.8'
services:
  nginx:
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - '8080:80'
    restart: always
  express:
    build:
      dockerfile: Dockerfile
      context: ./express
    ports:
      - '5000:5000'
    env_file:
      - .env
    restart: always
  react:
    build:
      dockerfile: Dockerfile
      context: ./react
    ports:
      - '9000:9000'
    restart: always
